apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "setup-2no.2no.io/v1alpha1",
          "kind": "Setup2no",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "tno-setup-operator",
              "app.kubernetes.io/instance": "setup2no-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "setup2no",
              "app.kubernetes.io/part-of": "tno-setup-operator"
            },
            "name": "setup2no-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-11-12T09:21:10Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: tno-setup-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Setup2no
      name: setup2noes.setup-2no.2no.io
      version: v1alpha1
  description: This Operator perform necessary actions in order to set up a two nodes
    highly avaliable openshift cluster
  displayName: 2NO Setup Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - setup-2no.2no.io
          resources:
          - setup2noes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - setup-2no.2no.io
          resources:
          - setup2noes/finalizers
          verbs:
          - update
        - apiGroups:
          - setup-2no.2no.io
          resources:
          - setup2noes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: tno-setup-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: tno-setup-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: tno-setup-operator
          control-plane: controller-manager
        name: tno-setup-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: tno-setup-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: tno-setup-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - remediation
  - auto-healing
  - recovery
  - high-availability
  - baremetal
  - two nodes
  - 2no
  - openshift
  links:
  - name: 2No Setup Operator
    url: https://tno-setup-operator.domain
  maintainers:
  - email: tbd@tbd.com
    name: TBD
  maturity: alpha
  provider:
    name: TBD
  version: 0.0.1
