# permissions for end users to view setup2noes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: setup2no-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tno-setup-operator
    app.kubernetes.io/part-of: tno-setup-operator
    app.kubernetes.io/managed-by: kustomize
  name: setup2no-viewer-role
rules:
- apiGroups:
  - setup-2no.2no.io
  resources:
  - setup2noes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - setup-2no.2no.io
  resources:
  - setup2noes/status
  verbs:
  - get
